### ISSUE TITLE
parse log message for context

### ISSUE THREAD

**Issue by nahakyuu** [yiisoft/yii-dev-panel#31]
https://github.com/yiisoft/yii-dev-panel/blob/469039abbccd2cbd81196486736e186db8aa3ead/src/Module/Debug/Component/Panel/LogPanel.tsx#L8-L28

for example: `$this->logger->info('hello {name}', ['name' => 'name'])`

**Comment by xepozz** [comment]
@nahakyuu would you like to contribute?
